
package org.codehaus.xfire.jaxws;

import javax.xml.ws.WebFault;

import org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ResourceUnknownFaultType;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-10/26/2005 09:05 PM(gnodet)
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "ResourceUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.xsd")
public class ResourceUnknownFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResourceUnknownFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ResourceUnknownFault(String message, ResourceUnknownFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ResourceUnknownFault(String message, ResourceUnknownFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ResourceUnknownFaultType
     */
    public ResourceUnknownFaultType getFaultInfo() {
        return faultInfo;
    }

}
