<?xml version='1.0' encoding='UTF-8'?>
<definitions name='common'
  targetNamespace='urn:xfire:generator:import-test'
  xmlns='http://schemas.xmlsoap.org/wsdl/'
  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:SOAP-ENC='http://schemas.xmlsoap.org/soap/encoding/'
  xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

  <types>
    <xsd:schema targetNamespace='urn:xfire:generator:import-test'
      xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

      <xsd:import namespace="urn:xfire:generator:import-test" schemaLocation="import.xsd"/>
      
      <xsd:element name="SomeStrings">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name='strings' type='xsd:string' maxOccurs="unbounded" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>

  <service name='CommonService'></service>
</definitions>
